version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "08:00"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    groups:
      all-dependencies:
        patterns:
          - "*"