[book]
authors = ["Lukas Schönmann"]
language = "en"
multilingual = false
src = "src"
title = "MerKurio Manual"
description = "This is the manual for the MerKurio command line tool."

[output.html]
default-theme = "rust"
smart-punctuation = true
git-repository-url = "https://github.com/lschoenm/MerKurio"